version: '3'
services:
  mongodb:
    image: mongo
    container_name: volunteer-db-container
    ports:
      - "27017:27017"
  data-importer:
    image: volunteer-db-image
    volumes:
      - ./volunteers.json:/volunteers.json
    command: sh -c "mongoimport --host mongodb --db volunteers_db --collection shifts --type json --file /volunteers.json --jsonArray"
    depends_on:
      - mongodb
